### ISSUE TITLE
Delete not working!

### ISSUE THREAD

**Issue by aadrian** [takezoe/gitbucket-maven-repository-plugin#14]
Hi,

The "Delete" operation seems to have no effect, i.e. the selected files (or directories), are still there after the button is pressed (even later, if the operation would be asynchronous).

This bug can be reproduced on Windows too (not just Linux) with the latest version of GitBucket (and the corresponding plug-in)

Thank you.

**Comment by ghost** [comment]
I'm facing the same problem.

[files.scala.html#L9](https://github.com/takezoe/gitbucket-maven-repository-plugin/blob/a4a3e346f287ca3c97f823a931be72ad99dc3af1/src/main/twirl/gitbucket/mavenrepository/files.scala.html#L9)

```
<input type="hidden" name="path" value="/@path">

----- 
  path = ""
  file = "xxx"
    => /xxx
 
  path = "xxx"
  file  = "yyy"
    => /xxxyyy
```

It seems that it works only if @path is empty.
