### ISSUE TITLE
NPM support!

### ISSUE THREAD

**Issue by aadrian** [takezoe/gitbucket-maven-repository-plugin#8]
Please add NPM support, i.e. the possibility to host not just private Java artifacts, but JavaScript artifacts too.

Thank you.

**Comment by takezoe** [comment]
I don't know the how I can implement the npm repository. Is there any documentation about that?

**Comment by aadrian** [comment]
@takezoe from the Java based servers, only Nexus seems to support NPM (but with mirroring and more complex features).

However there are quite a few that are implemented in JavaScript:
https://www.npmjs.com/package/sinopia

or https://medium.com/engenharia-noalvo/ways-to-have-your-private-npm-registry-and-a-final-diy-solution-eed001a88e74

> Is there any documentation about that?

Unfortunately I'm not aware of any official documentation at this moment, but it seems tha even a Git repo can be used as a "npm registry" (it's just missing some features).

**Comment by aadrian** [comment]
Needs to be done as a separate plug-in, since there does not seems to be much in common with Maven: https://github.com/aadrian/gitbucket-npm-repository-plugin
